package db.entity.bridge;

import java.util.List;
import java.lang.Integer;
import db.entity.Car;
import db.entity.Customer;
import db.interfaces.*;
import db.entity.CarFueling;
import java.sql.SQLException;
import java.lang.String;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.FuelEnum;
import visitor.Visitor;

@AutoGenerated
public class CarBridge implements IEntityBridge {

	private static final String TableName = "car";

	private static Object _lock = new Object();
	private static CarBridge _instance;
	
	private CarBridge() {}

	public static CarBridge getInstance() {
		if (_instance == null) {
			synchronized(_lock) {
				if (_instance == null) {
					_instance = new CarBridge();
				}
			}
		}
		return _instance;
	}

	public IEntity createEntity() {
		return new Car();
	}

	@Override
	public void populateEntity(IEntity ientity, IGetValue<Integer, String, Object, Object> iterator) throws SQLException, InterruptedException {
		Car entity = (Car) ientity;
		entity.setId((Integer) iterator.get(0, "id", entity.getId()));
		entity.setPlateNumber((String) iterator.get(1, "plate_number", entity.getPlateNumber()));
		entity.setCustomer((Customer) iterator.get(2, "customer_fk", entity.getCustomer()));
		entity.setFuelEnum((FuelEnum) iterator.get(3, "fuel_enum_fk", entity.getFuelEnum()));
		entity.setCarFueling((CarFueling) iterator.get(4, "car_fueling_fk", entity.getCarFueling()));
	}

	@Override
	public void collectFromEntity(IEntity ientity, ISetValue<Integer, String, Object> iterator) throws SQLException, InterruptedException {
		Car entity = (Car) ientity;
		iterator.set(0, "id", entity.getId());
		iterator.set(1, "plate_number", entity.getPlateNumber());
		iterator.set(2, "customer_fk", entity.getCustomer());
		iterator.set(3, "fuel_enum_fk", entity.getFuelEnum());
		iterator.set(4, "car_fueling_fk", entity.getCarFueling());
	}

	@Override
	public void accept(IEntity entity, Visitor visitor) {
		visitor.visit((Car) entity);
	}

	@Override
	public String getTableName() {
		return TableName;
	}

	@Override
	public List<IEntity> getForeignEntities(IEntity ientity) {
		Car entity = (Car) ientity;
		List<IEntity> list = new ArrayList<IEntity>();
		list.add(entity.getCustomer());
		list.add(entity.getFuelEnum());
		list.add(entity.getCarFueling());
		return list;
	}
}
