package db.entity.bridge;

import java.util.List;
import java.lang.Integer;
import java.lang.Boolean;
import db.interfaces.*;
import db.entity.FuelCompanyEnum;
import java.lang.Double;
import java.sql.SQLException;
import java.lang.String;
import annotations.AutoGenerated;
import java.util.ArrayList;
import visitor.Visitor;

@AutoGenerated
public class FuelCompanyEnumBridge implements IEntityBridge {

	private static final String TableName = "fuel_company_enum";

	private static Object _lock = new Object();
	private static FuelCompanyEnumBridge _instance;
	
	private FuelCompanyEnumBridge() {}

	public static FuelCompanyEnumBridge getInstance() {
		if (_instance == null) {
			synchronized(_lock) {
				if (_instance == null) {
					_instance = new FuelCompanyEnumBridge();
				}
			}
		}
		return _instance;
	}

	public IEntity createEntity() {
		return new FuelCompanyEnum();
	}

	@Override
	public void populateEntity(IEntity ientity, IGetValue<Integer, String, Object, Object> iterator) throws SQLException, InterruptedException {
		FuelCompanyEnum entity = (FuelCompanyEnum) ientity;
		entity.setId((Integer) iterator.get(0, "id", entity.getId()));
		entity.setCompanyNameKey((String) iterator.get(1, "company_name_key", entity.getCompanyNameKey()));
		entity.setCompanyDiscount((Double) iterator.get(2, "company_discount", entity.getCompanyDiscount()));
		entity.setCompanyDiscountRequest((Double) iterator.get(3, "company_discount_request", entity.getCompanyDiscountRequest()));
		entity.setRequestHandled((Boolean) iterator.get(4, "request_handled", entity.getRequestHandled()));
	}

	@Override
	public void collectFromEntity(IEntity ientity, ISetValue<Integer, String, Object> iterator) throws SQLException, InterruptedException {
		FuelCompanyEnum entity = (FuelCompanyEnum) ientity;
		iterator.set(0, "id", entity.getId());
		iterator.set(1, "company_name_key", entity.getCompanyNameKey());
		iterator.set(2, "company_discount", entity.getCompanyDiscount());
		iterator.set(3, "company_discount_request", entity.getCompanyDiscountRequest());
		iterator.set(4, "request_handled", entity.getRequestHandled());
	}

	@Override
	public void accept(IEntity entity, Visitor visitor) {
		visitor.visit((FuelCompanyEnum) entity);
	}

	@Override
	public String getTableName() {
		return TableName;
	}

	@Override
	public List<IEntity> getForeignEntities(IEntity ientity) {
		FuelCompanyEnum entity = (FuelCompanyEnum) ientity;
		List<IEntity> list = new ArrayList<IEntity>();

		return list;
	}
}
