package db.entity.bridge;

import java.util.List;
import java.lang.Integer;
import db.entity.MarketingManagerReports;
import db.interfaces.*;
import java.sql.SQLException;
import java.lang.String;
import annotations.AutoGenerated;
import java.util.ArrayList;
import visitor.Visitor;

@AutoGenerated
public class MarketingManagerReportsBridge implements IEntityBridge {

	private static final String TableName = "marketing_manager_reports";

	private static Object _lock = new Object();
	private static MarketingManagerReportsBridge _instance;
	
	private MarketingManagerReportsBridge() {}

	public static MarketingManagerReportsBridge getInstance() {
		if (_instance == null) {
			synchronized(_lock) {
				if (_instance == null) {
					_instance = new MarketingManagerReportsBridge();
				}
			}
		}
		return _instance;
	}

	public IEntity createEntity() {
		return new MarketingManagerReports();
	}

	@Override
	public void populateEntity(IEntity ientity, IGetValue<Integer, String, Object, Object> iterator) throws SQLException, InterruptedException {
		MarketingManagerReports entity = (MarketingManagerReports) ientity;
		entity.setId((Integer) iterator.get(0, "id", entity.getId()));
		entity.setReportType((String) iterator.get(1, "report_type", entity.getReportType()));
	}

	@Override
	public void collectFromEntity(IEntity ientity, ISetValue<Integer, String, Object> iterator) throws SQLException, InterruptedException {
		MarketingManagerReports entity = (MarketingManagerReports) ientity;
		iterator.set(0, "id", entity.getId());
		iterator.set(1, "report_type", entity.getReportType());
	}

	@Override
	public void accept(IEntity entity, Visitor visitor) {
		visitor.visit((MarketingManagerReports) entity);
	}

	@Override
	public String getTableName() {
		return TableName;
	}

	@Override
	public List<IEntity> getForeignEntities(IEntity ientity) {
		MarketingManagerReports entity = (MarketingManagerReports) ientity;
		List<IEntity> list = new ArrayList<IEntity>();

		return list;
	}
}
