package db.entity.bridge;

import java.util.List;
import java.lang.Integer;
import db.entity.OrderUrgencyEnum;
import db.interfaces.*;
import java.lang.Double;
import java.sql.SQLException;
import java.lang.String;
import annotations.AutoGenerated;
import java.util.ArrayList;
import visitor.Visitor;

@AutoGenerated
public class OrderUrgencyEnumBridge implements IEntityBridge {

	private static final String TableName = "order_urgency_enum";

	private static Object _lock = new Object();
	private static OrderUrgencyEnumBridge _instance;
	
	private OrderUrgencyEnumBridge() {}

	public static OrderUrgencyEnumBridge getInstance() {
		if (_instance == null) {
			synchronized(_lock) {
				if (_instance == null) {
					_instance = new OrderUrgencyEnumBridge();
				}
			}
		}
		return _instance;
	}

	public IEntity createEntity() {
		return new OrderUrgencyEnum();
	}

	@Override
	public void populateEntity(IEntity ientity, IGetValue<Integer, String, Object, Object> iterator) throws SQLException, InterruptedException {
		OrderUrgencyEnum entity = (OrderUrgencyEnum) ientity;
		entity.setId((Integer) iterator.get(0, "id", entity.getId()));
		entity.setOrderUrgencyKey((String) iterator.get(1, "order_urgency_key", entity.getOrderUrgencyKey()));
		entity.setExtraDeliveryPrice((Double) iterator.get(2, "extra_delivery_price", entity.getExtraDeliveryPrice()));
		entity.setEstimatedDeliveryHours((Double) iterator.get(3, "estimated_delivery_hours", entity.getEstimatedDeliveryHours()));
	}

	@Override
	public void collectFromEntity(IEntity ientity, ISetValue<Integer, String, Object> iterator) throws SQLException, InterruptedException {
		OrderUrgencyEnum entity = (OrderUrgencyEnum) ientity;
		iterator.set(0, "id", entity.getId());
		iterator.set(1, "order_urgency_key", entity.getOrderUrgencyKey());
		iterator.set(2, "extra_delivery_price", entity.getExtraDeliveryPrice());
		iterator.set(3, "estimated_delivery_hours", entity.getEstimatedDeliveryHours());
	}

	@Override
	public void accept(IEntity entity, Visitor visitor) {
		visitor.visit((OrderUrgencyEnum) entity);
	}

	@Override
	public String getTableName() {
		return TableName;
	}

	@Override
	public List<IEntity> getForeignEntities(IEntity ientity) {
		OrderUrgencyEnum entity = (OrderUrgencyEnum) ientity;
		List<IEntity> list = new ArrayList<IEntity>();

		return list;
	}
}
