package db.entity.bridge;

import java.lang.Integer;
import db.interfaces.*;
import java.sql.SQLException;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.sql.Timestamp;
import db.entity.FuelEnum;
import visitor.Visitor;
import java.util.List;
import db.entity.Station;
import db.entity.StationSupplyOrder;
import java.lang.Double;
import java.lang.String;

@AutoGenerated
public class StationSupplyOrderBridge implements IEntityBridge {

	private static final String TableName = "station_supply_order";

	private static Object _lock = new Object();
	private static StationSupplyOrderBridge _instance;
	
	private StationSupplyOrderBridge() {}

	public static StationSupplyOrderBridge getInstance() {
		if (_instance == null) {
			synchronized(_lock) {
				if (_instance == null) {
					_instance = new StationSupplyOrderBridge();
				}
			}
		}
		return _instance;
	}

	public IEntity createEntity() {
		return new StationSupplyOrder();
	}

	@Override
	public void populateEntity(IEntity ientity, IGetValue<Integer, String, Object, Object> iterator) throws SQLException, InterruptedException {
		StationSupplyOrder entity = (StationSupplyOrder) ientity;
		entity.setId((Integer) iterator.get(0, "id", entity.getId()));
		entity.setOrderId((Integer) iterator.get(1, "order_id", entity.getOrderId()));
		entity.setOrderDate((Timestamp) iterator.get(2, "order_date", entity.getOrderDate()));
		entity.setAmount((Double) iterator.get(3, "amount", entity.getAmount()));
		entity.setOrderStatus((String) iterator.get(4, "order_status", entity.getOrderStatus()));
		entity.setTotalPrice((Double) iterator.get(5, "total_price", entity.getTotalPrice()));
		entity.setFuelEnum((FuelEnum) iterator.get(6, "fuel_enum_fk", entity.getFuelEnum()));
		entity.setStation((Station) iterator.get(7, "station_fk", entity.getStation()));
	}

	@Override
	public void collectFromEntity(IEntity ientity, ISetValue<Integer, String, Object> iterator) throws SQLException, InterruptedException {
		StationSupplyOrder entity = (StationSupplyOrder) ientity;
		iterator.set(0, "id", entity.getId());
		iterator.set(1, "order_id", entity.getOrderId());
		iterator.set(2, "order_date", entity.getOrderDate());
		iterator.set(3, "amount", entity.getAmount());
		iterator.set(4, "order_status", entity.getOrderStatus());
		iterator.set(5, "total_price", entity.getTotalPrice());
		iterator.set(6, "fuel_enum_fk", entity.getFuelEnum());
		iterator.set(7, "station_fk", entity.getStation());
	}

	@Override
	public void accept(IEntity entity, Visitor visitor) {
		visitor.visit((StationSupplyOrder) entity);
	}

	@Override
	public String getTableName() {
		return TableName;
	}

	@Override
	public List<IEntity> getForeignEntities(IEntity ientity) {
		StationSupplyOrder entity = (StationSupplyOrder) ientity;
		List<IEntity> list = new ArrayList<IEntity>();
		list.add(entity.getFuelEnum());
		list.add(entity.getStation());
		return list;
	}
}
