package db.entity.bridge;

import java.util.List;
import java.lang.Integer;
import db.interfaces.*;
import java.lang.Double;
import java.sql.SQLException;
import java.lang.String;
import annotations.AutoGenerated;
import java.util.ArrayList;
import visitor.Visitor;
import db.entity.SubscriptionPlanRatesEnum;

@AutoGenerated
public class SubscriptionPlanRatesEnumBridge implements IEntityBridge {

	private static final String TableName = "subscription_plan_rates_enum";

	private static Object _lock = new Object();
	private static SubscriptionPlanRatesEnumBridge _instance;
	
	private SubscriptionPlanRatesEnumBridge() {}

	public static SubscriptionPlanRatesEnumBridge getInstance() {
		if (_instance == null) {
			synchronized(_lock) {
				if (_instance == null) {
					_instance = new SubscriptionPlanRatesEnumBridge();
				}
			}
		}
		return _instance;
	}

	public IEntity createEntity() {
		return new SubscriptionPlanRatesEnum();
	}

	@Override
	public void populateEntity(IEntity ientity, IGetValue<Integer, String, Object, Object> iterator) throws SQLException, InterruptedException {
		SubscriptionPlanRatesEnum entity = (SubscriptionPlanRatesEnum) ientity;
		entity.setId((Integer) iterator.get(0, "id", entity.getId()));
		entity.setPlanTypeKey((String) iterator.get(1, "plan_type_key", entity.getPlanTypeKey()));
		entity.setDiscount((Double) iterator.get(2, "discount", entity.getDiscount()));
	}

	@Override
	public void collectFromEntity(IEntity ientity, ISetValue<Integer, String, Object> iterator) throws SQLException, InterruptedException {
		SubscriptionPlanRatesEnum entity = (SubscriptionPlanRatesEnum) ientity;
		iterator.set(0, "id", entity.getId());
		iterator.set(1, "plan_type_key", entity.getPlanTypeKey());
		iterator.set(2, "discount", entity.getDiscount());
	}

	@Override
	public void accept(IEntity entity, Visitor visitor) {
		visitor.visit((SubscriptionPlanRatesEnum) entity);
	}

	@Override
	public String getTableName() {
		return TableName;
	}

	@Override
	public List<IEntity> getForeignEntities(IEntity ientity) {
		SubscriptionPlanRatesEnum entity = (SubscriptionPlanRatesEnum) ientity;
		List<IEntity> list = new ArrayList<IEntity>();

		return list;
	}
}
