package db.entity.bridge;

import java.util.List;
import java.lang.Integer;
import db.entity.Customer;
import db.entity.SubscriptionPlan;
import db.interfaces.*;
import db.entity.FuelCompanyEnum;
import java.sql.SQLException;
import annotations.AutoGenerated;
import java.util.ArrayList;
import visitor.Visitor;
import db.entity.SubscriptionPlanRatesEnum;

@AutoGenerated
public class SubscriptionPlanBridge implements IEntityBridge {

	private static final String TableName = "subscription_plan";

	private static Object _lock = new Object();
	private static SubscriptionPlanBridge _instance;
	
	private SubscriptionPlanBridge() {}

	public static SubscriptionPlanBridge getInstance() {
		if (_instance == null) {
			synchronized(_lock) {
				if (_instance == null) {
					_instance = new SubscriptionPlanBridge();
				}
			}
		}
		return _instance;
	}

	public IEntity createEntity() {
		return new SubscriptionPlan();
	}

	@Override
	public void populateEntity(IEntity ientity, IGetValue<Integer, String, Object, Object> iterator) throws SQLException, InterruptedException {
		SubscriptionPlan entity = (SubscriptionPlan) ientity;
		entity.setId((Integer) iterator.get(0, "id", entity.getId()));
		entity.setFuelCompanyEnum((FuelCompanyEnum) iterator.get(1, "fuel_company_enum_fk", entity.getFuelCompanyEnum()));
		entity.setCustomer((Customer) iterator.get(2, "customer_fk", entity.getCustomer()));
		entity.setSubscriptionPlanRatesEnum((SubscriptionPlanRatesEnum) iterator.get(3, "subscription_plan_rates_enum_fk", entity.getSubscriptionPlanRatesEnum()));
	}

	@Override
	public void collectFromEntity(IEntity ientity, ISetValue<Integer, String, Object> iterator) throws SQLException, InterruptedException {
		SubscriptionPlan entity = (SubscriptionPlan) ientity;
		iterator.set(0, "id", entity.getId());
		iterator.set(1, "fuel_company_enum_fk", entity.getFuelCompanyEnum());
		iterator.set(2, "customer_fk", entity.getCustomer());
		iterator.set(3, "subscription_plan_rates_enum_fk", entity.getSubscriptionPlanRatesEnum());
	}

	@Override
	public void accept(IEntity entity, Visitor visitor) {
		visitor.visit((SubscriptionPlan) entity);
	}

	@Override
	public String getTableName() {
		return TableName;
	}

	@Override
	public List<IEntity> getForeignEntities(IEntity ientity) {
		SubscriptionPlan entity = (SubscriptionPlan) ientity;
		List<IEntity> list = new ArrayList<IEntity>();
		list.add(entity.getFuelCompanyEnum());
		list.add(entity.getCustomer());
		list.add(entity.getSubscriptionPlanRatesEnum());
		return list;
	}
}
