package visitor;

import db.entity.Reports;
import db.entity.Employee;
import db.entity.ReportsInfo;
import annotations.AutoGenerated;
import db.entity.CheckingEnum;

@AutoGenerated
public class Visitor {

	public void visit(ReportsInfo reportsinfo) { };

	public void visit(Reports reports) { };

	public void visit(Employee employee) { };

	public void visit(CheckingEnum checkingenum) { };

}