package visitor;

import db.entity.HomeHeatingDiscountEnum;
import db.entity.CustomersRatingsView;
import db.entity.SubscriptionPlan;
import db.entity.FuelingPurchase;
import db.entity.Driver;
import db.entity.SpecialSalesEnum;
import db.entity.Payment;
import db.entity.FuelEnum;
import db.entity.OrderUrgencyEnum;
import db.entity.StationSupplyOrder;
import db.entity.SubscriptionPlanRatesEnum;
import db.entity.StationsFuel;
import db.entity.CustomersView;
import db.entity.Customer;
import db.entity.CustomersRatings;
import db.entity.PricingModelEnum;
import db.entity.MarketingManagerReports;
import db.entity.CarFueling;
import db.entity.FuelCompanyEnum;
import db.entity.StationManagerReports;
import annotations.AutoGenerated;
import db.entity.Address;
import db.entity.Car;
import db.entity.Station;
import db.entity.SpecialSalesHistory;
import db.entity.Employee;
import db.entity.SystemUser;
import db.entity.HomeHeatingOrder;
import db.entity.AnalyticalView;
import db.entity.AnalyticalRatings;
import db.entity.Person;

@AutoGenerated
public class Visitor {

	public void visit(Address address) { };

	public void visit(AnalyticalRatings analyticalratings) { };

	public void visit(Car car) { };

	public void visit(CarFueling carfueling) { };

	public void visit(Customer customer) { };

	public void visit(CustomersRatings customersratings) { };

	public void visit(Driver driver) { };

	public void visit(Employee employee) { };

	public void visit(FuelCompanyEnum fuelcompanyenum) { };

	public void visit(FuelEnum fuelenum) { };

	public void visit(FuelingPurchase fuelingpurchase) { };

	public void visit(HomeHeatingDiscountEnum homeheatingdiscountenum) { };

	public void visit(HomeHeatingOrder homeheatingorder) { };

	public void visit(MarketingManagerReports marketingmanagerreports) { };

	public void visit(OrderUrgencyEnum orderurgencyenum) { };

	public void visit(Payment payment) { };

	public void visit(Person person) { };

	public void visit(PricingModelEnum pricingmodelenum) { };

	public void visit(SpecialSalesEnum specialsalesenum) { };

	public void visit(SpecialSalesHistory specialsaleshistory) { };

	public void visit(Station station) { };

	public void visit(StationManagerReports stationmanagerreports) { };

	public void visit(StationSupplyOrder stationsupplyorder) { };

	public void visit(StationsFuel stationsfuel) { };

	public void visit(SubscriptionPlan subscriptionplan) { };

	public void visit(SubscriptionPlanRatesEnum subscriptionplanratesenum) { };

	public void visit(SystemUser systemuser) { };

	public void visit(AnalyticalView analyticalview) { };

	public void visit(CustomersRatingsView customersratingsview) { };

	public void visit(CustomersView customersview) { };

}