package db.services;

import db.entity.bridge.FuelingPurchaseBridge;
import db.entity.bridge.StationSupplyOrderBridge;
import db.entity.bridge.DriverBridge;
import db.entity.bridge.HomeHeatingDiscountEnumBridge;
import db.entity.bridge.EmployeeBridge;
import db.entity.bridge.PersonBridge;
import db.entity.bridge.SpecialSalesHistoryBridge;
import db.entity.bridge.CustomerBridge;
import db.entity.bridge.PaymentBridge;
import db.entity.bridge.CarFuelingBridge;
import db.entity.bridge.AnalyticalRatingsBridge;
import db.entity.bridge.SystemUserBridge;
import db.entity.bridge.StationManagerReportsBridge;
import db.entity.bridge.CustomersViewBridge;
import db.entity.bridge.AnalyticalViewBridge;
import db.entity.bridge.AddressBridge;
import db.entity.bridge.MarketingManagerReportsBridge;
import db.entity.bridge.HomeHeatingOrderBridge;
import db.entity.bridge.FuelCompanyEnumBridge;
import db.entity.bridge.SpecialSalesEnumBridge;
import db.entity.bridge.CustomersRatingsBridge;
import db.interfaces.*;
import db.entity.bridge.SubscriptionPlanBridge;
import annotations.AutoGenerated;
import db.entity.bridge.FuelEnumBridge;
import java.util.HashMap;
import db.entity.bridge.StationsFuelBridge;
import db.entity.bridge.SubscriptionPlanRatesEnumBridge;
import db.entity.bridge.CustomersRatingsViewBridge;
import java.util.Map;
import db.entity.bridge.StationBridge;
import db.entity.bridge.OrderUrgencyEnumBridge;
import db.entity.bridge.PricingModelEnumBridge;
import db.entity.bridge.CarBridge;
import java.util.Set;

@AutoGenerated
public class Services {

	public interface Instansiate<T> {
		T create();
	}

	private static Map<String, IEntityBridge> _bridgeMap = 
			new HashMap<String, IEntityBridge>();

	public static void initialize() {
		_bridgeMap.put("address", AddressBridge.getInstance());
		_bridgeMap.put("analytical_ratings", AnalyticalRatingsBridge.getInstance());
		_bridgeMap.put("car", CarBridge.getInstance());
		_bridgeMap.put("car_fueling", CarFuelingBridge.getInstance());
		_bridgeMap.put("customer", CustomerBridge.getInstance());
		_bridgeMap.put("customers_ratings", CustomersRatingsBridge.getInstance());
		_bridgeMap.put("driver", DriverBridge.getInstance());
		_bridgeMap.put("employee", EmployeeBridge.getInstance());
		_bridgeMap.put("fuel_company_enum", FuelCompanyEnumBridge.getInstance());
		_bridgeMap.put("fuel_enum", FuelEnumBridge.getInstance());
		_bridgeMap.put("fueling_purchase", FuelingPurchaseBridge.getInstance());
		_bridgeMap.put("home_heating_discount_enum", HomeHeatingDiscountEnumBridge.getInstance());
		_bridgeMap.put("home_heating_order", HomeHeatingOrderBridge.getInstance());
		_bridgeMap.put("marketing_manager_reports", MarketingManagerReportsBridge.getInstance());
		_bridgeMap.put("order_urgency_enum", OrderUrgencyEnumBridge.getInstance());
		_bridgeMap.put("payment", PaymentBridge.getInstance());
		_bridgeMap.put("person", PersonBridge.getInstance());
		_bridgeMap.put("pricing_model_enum", PricingModelEnumBridge.getInstance());
		_bridgeMap.put("special_sales_enum", SpecialSalesEnumBridge.getInstance());
		_bridgeMap.put("special_sales_history", SpecialSalesHistoryBridge.getInstance());
		_bridgeMap.put("station", StationBridge.getInstance());
		_bridgeMap.put("station_manager_reports", StationManagerReportsBridge.getInstance());
		_bridgeMap.put("station_supply_order", StationSupplyOrderBridge.getInstance());
		_bridgeMap.put("stations_fuel", StationsFuelBridge.getInstance());
		_bridgeMap.put("subscription_plan", SubscriptionPlanBridge.getInstance());
		_bridgeMap.put("subscription_plan_rates_enum", SubscriptionPlanRatesEnumBridge.getInstance());
		_bridgeMap.put("system_user", SystemUserBridge.getInstance());
		_bridgeMap.put("analytical_view", AnalyticalViewBridge.getInstance());
		_bridgeMap.put("customers_ratings_view", CustomersRatingsViewBridge.getInstance());
		_bridgeMap.put("customers_view", CustomersViewBridge.getInstance());
	}

	public static IEntityBridge getBridge(String table) {
		return _bridgeMap.get(table);
	}

	public static Set<String> getTables() {
		return _bridgeMap.keySet();
	}

}