package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="address")
public class Address implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="city", Index=1)
	private String _city;

	@Column(Name="street", Index=2)
	private String _street;

	@Column(Name="house", Index=3)
	private String _house;

	@Column(Name="floor", Index=4)
	private Integer _floor;

	@Column(Name="apartment", Index=5)
	private String _apartment;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getCity() {
		return _city;
	}

	public void setCity(String city) {
		_city = city;
	}

	public String getStreet() {
		return _street;
	}

	public void setStreet(String street) {
		_street = street;
	}

	public String getHouse() {
		return _house;
	}

	public void setHouse(String house) {
		_house = house;
	}

	public Integer getFloor() {
		return _floor;
	}

	public void setFloor(Integer floor) {
		_floor = floor;
	}

	public String getApartment() {
		return _apartment;
	}

	public void setApartment(String apartment) {
		_apartment = apartment;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_city != null) {
			list.add("	city: " + _city);
		}
		if (_street != null) {
			list.add("	street: " + _street);
		}
		if (_house != null) {
			list.add("	house: " + _house);
		}
		if (_floor != null) {
			list.add("	floor: " + _floor);
		}
		if (_apartment != null) {
			list.add("	apartment: " + _apartment);
		}
		return "table address:\n" + String.join("\n", list);
	}

}