package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import java.sql.Time;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="analytical_ratings")
public class AnalyticalRatings implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="customer_pricing_model", Index=1)
	private String _customer_pricing_model;

	@Column(Name="fuel_type", Index=2)
	private String _fuel_type;

	@Column(Name="start_fueling_time", Index=3)
	private Time _start_fueling_time;

	@Column(Name="end_fueling_time", Index=4)
	private Time _end_fueling_time;

	@Column(Name="rating", Index=5)
	private Integer _rating;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getCustomerPricingModel() {
		return _customer_pricing_model;
	}

	public void setCustomerPricingModel(String customer_pricing_model) {
		_customer_pricing_model = customer_pricing_model;
	}

	public String getFuelType() {
		return _fuel_type;
	}

	public void setFuelType(String fuel_type) {
		_fuel_type = fuel_type;
	}

	public Time getStartFuelingTime() {
		return _start_fueling_time;
	}

	public void setStartFuelingTime(Time start_fueling_time) {
		_start_fueling_time = start_fueling_time;
	}

	public Time getEndFuelingTime() {
		return _end_fueling_time;
	}

	public void setEndFuelingTime(Time end_fueling_time) {
		_end_fueling_time = end_fueling_time;
	}

	public Integer getRating() {
		return _rating;
	}

	public void setRating(Integer rating) {
		_rating = rating;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_customer_pricing_model != null) {
			list.add("	customer_pricing_model: " + _customer_pricing_model);
		}
		if (_fuel_type != null) {
			list.add("	fuel_type: " + _fuel_type);
		}
		if (_start_fueling_time != null) {
			list.add("	start_fueling_time: " + _start_fueling_time);
		}
		if (_end_fueling_time != null) {
			list.add("	end_fueling_time: " + _end_fueling_time);
		}
		if (_rating != null) {
			list.add("	rating: " + _rating);
		}
		return "table analytical_ratings:\n" + String.join("\n", list);
	}

}