package db.entity;

import java.util.List;
import java.lang.Integer;
import db.entity.Customer;
import annotations.Column;
import db.entity.CarFueling;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.FuelEnum;

@AutoGenerated
@Table(Name="car")
public class Car implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="plate_number", Index=1)
	private String _plate_number;

	@Column(Name="customer_fk", Index=2)
	@Table(Name="customer")
	private Customer _customer;

	@Column(Name="fuel_enum_fk", Index=3)
	@Table(Name="fuel_enum")
	private FuelEnum _fuel_enum;

	@Column(Name="car_fueling_fk", Index=4)
	@Table(Name="car_fueling")
	private CarFueling _car_fueling;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getPlateNumber() {
		return _plate_number;
	}

	public void setPlateNumber(String plate_number) {
		_plate_number = plate_number;
	}

	public Customer getCustomer() {
		return _customer;
	}

	public void setCustomer(Customer customer) {
		_customer = customer;
	}

	public FuelEnum getFuelEnum() {
		return _fuel_enum;
	}

	public void setFuelEnum(FuelEnum fuel_enum) {
		_fuel_enum = fuel_enum;
	}

	public CarFueling getCarFueling() {
		return _car_fueling;
	}

	public void setCarFueling(CarFueling car_fueling) {
		_car_fueling = car_fueling;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_plate_number != null) {
			list.add("	plate_number: " + _plate_number);
		}
		if (_customer != null) {
			list.add("	customer: " + _customer);
		}
		if (_fuel_enum != null) {
			list.add("	fuel_enum: " + _fuel_enum);
		}
		if (_car_fueling != null) {
			list.add("	car_fueling: " + _car_fueling);
		}
		return "table car:\n" + String.join("\n", list);
	}

}