package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="car_fueling")
public class CarFueling implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="monthly_fuel_amount", Index=1)
	private Double _monthly_fuel_amount;

	@Column(Name="month_of_fuel", Index=2)
	private String _month_of_fuel;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Double getMonthlyFuelAmount() {
		return _monthly_fuel_amount;
	}

	public void setMonthlyFuelAmount(Double monthly_fuel_amount) {
		_monthly_fuel_amount = monthly_fuel_amount;
	}

	public String getMonthOfFuel() {
		return _month_of_fuel;
	}

	public void setMonthOfFuel(String month_of_fuel) {
		_month_of_fuel = month_of_fuel;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_monthly_fuel_amount != null) {
			list.add("	monthly_fuel_amount: " + _monthly_fuel_amount);
		}
		if (_month_of_fuel != null) {
			list.add("	month_of_fuel: " + _month_of_fuel);
		}
		return "table car_fueling:\n" + String.join("\n", list);
	}

}