package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="checking_enum")
public class CheckingEnum implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="title", Index=1)
	private String _title;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getTitle() {
		return _title;
	}

	public void setTitle(String title) {
		_title = title;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_title != null) {
			list.add("	title: " + _title);
		}
		return "table checking_enum:\n" + String.join("\n", list);
	}

}