package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.sql.Timestamp;

@AutoGenerated
@Table(Name="customers_ratings_view")
public class CustomersRatingsView implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="model_type", Index=1)
	private String _model_type;

	@Column(Name="fueling_date_time", Index=2)
	private Timestamp _fueling_date_time;

	@Column(Name="fuel_type_key", Index=3)
	private String _fuel_type_key;

	@Column(Name="analytical_rating", Index=4)
	private Double _analytical_rating;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getModelType() {
		return _model_type;
	}

	public void setModelType(String model_type) {
		_model_type = model_type;
	}

	public Timestamp getFuelingDateTime() {
		return _fueling_date_time;
	}

	public void setFuelingDateTime(Timestamp fueling_date_time) {
		_fueling_date_time = fueling_date_time;
	}

	public String getFuelTypeKey() {
		return _fuel_type_key;
	}

	public void setFuelTypeKey(String fuel_type_key) {
		_fuel_type_key = fuel_type_key;
	}

	public Double getAnalyticalRating() {
		return _analytical_rating;
	}

	public void setAnalyticalRating(Double analytical_rating) {
		_analytical_rating = analytical_rating;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_model_type != null) {
			list.add("	model_type: " + _model_type);
		}
		if (_fueling_date_time != null) {
			list.add("	fueling_date_time: " + _fueling_date_time);
		}
		if (_fuel_type_key != null) {
			list.add("	fuel_type_key: " + _fuel_type_key);
		}
		if (_analytical_rating != null) {
			list.add("	analytical_rating: " + _analytical_rating);
		}
		return "table customers_ratings_view:\n" + String.join("\n", list);
	}

}