package db.entity;

import java.lang.Integer;
import db.entity.PricingModelEnum;
import annotations.Column;
import java.io.Serializable;
import db.entity.Payment;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.sql.Timestamp;
import db.entity.Address;
import java.util.List;
import db.interfaces.IEntity;
import java.lang.Double;
import db.entity.SystemUser;
import java.lang.String;
import annotations.Table;
import db.entity.Person;

@AutoGenerated
@Table(Name="customer")
public class Customer implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="customer_id", Index=1)
	private Integer _customer_id;

	@Column(Name="customer_type", Index=2)
	private String _customer_type;

	@Column(Name="company_name", Index=3)
	private String _company_name;

	@Column(Name="rating", Index=4)
	private Double _rating;

	@Column(Name="last_rating_time", Index=5)
	private Timestamp _last_rating_time;

	@Column(Name="address_fk", Index=6)
	@Table(Name="address")
	private Address _address;

	@Column(Name="pricing_model_enum_fk", Index=7)
	@Table(Name="pricing_model_enum")
	private PricingModelEnum _pricing_model_enum;

	@Column(Name="system_user_fk", Index=8)
	@Table(Name="system_user")
	private SystemUser _system_user;

	@Column(Name="person_fk", Index=9)
	@Table(Name="person")
	private Person _person;

	@Column(Name="payment_fk", Index=10)
	@Table(Name="payment")
	private Payment _payment;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Integer getCustomerId() {
		return _customer_id;
	}

	public void setCustomerId(Integer customer_id) {
		_customer_id = customer_id;
	}

	public String getCustomerType() {
		return _customer_type;
	}

	public void setCustomerType(String customer_type) {
		_customer_type = customer_type;
	}

	public String getCompanyName() {
		return _company_name;
	}

	public void setCompanyName(String company_name) {
		_company_name = company_name;
	}

	public Double getRating() {
		return _rating;
	}

	public void setRating(Double rating) {
		_rating = rating;
	}

	public Timestamp getLastRatingTime() {
		return _last_rating_time;
	}

	public void setLastRatingTime(Timestamp last_rating_time) {
		_last_rating_time = last_rating_time;
	}

	public Address getAddress() {
		return _address;
	}

	public void setAddress(Address address) {
		_address = address;
	}

	public PricingModelEnum getPricingModelEnum() {
		return _pricing_model_enum;
	}

	public void setPricingModelEnum(PricingModelEnum pricing_model_enum) {
		_pricing_model_enum = pricing_model_enum;
	}

	public SystemUser getSystemUser() {
		return _system_user;
	}

	public void setSystemUser(SystemUser system_user) {
		_system_user = system_user;
	}

	public Person getPerson() {
		return _person;
	}

	public void setPerson(Person person) {
		_person = person;
	}

	public Payment getPayment() {
		return _payment;
	}

	public void setPayment(Payment payment) {
		_payment = payment;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_customer_id != null) {
			list.add("	customer_id: " + _customer_id);
		}
		if (_customer_type != null) {
			list.add("	customer_type: " + _customer_type);
		}
		if (_company_name != null) {
			list.add("	company_name: " + _company_name);
		}
		if (_rating != null) {
			list.add("	rating: " + _rating);
		}
		if (_last_rating_time != null) {
			list.add("	last_rating_time: " + _last_rating_time);
		}
		if (_address != null) {
			list.add("	address: " + _address);
		}
		if (_pricing_model_enum != null) {
			list.add("	pricing_model_enum: " + _pricing_model_enum);
		}
		if (_system_user != null) {
			list.add("	system_user: " + _system_user);
		}
		if (_person != null) {
			list.add("	person: " + _person);
		}
		if (_payment != null) {
			list.add("	payment: " + _payment);
		}
		return "table customer:\n" + String.join("\n", list);
	}

}