package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.sql.Timestamp;
import db.entity.AnalyticalRatings;

@AutoGenerated
@Table(Name="customers_ratings")
public class CustomersRatings implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="customer_id", Index=1)
	private Integer _customer_id;

	@Column(Name="customer_pricing_model", Index=2)
	private String _customer_pricing_model;

	@Column(Name="fuel_type", Index=3)
	private String _fuel_type;

	@Column(Name="fueling_purchase_hour", Index=4)
	private Timestamp _fueling_purchase_hour;

	@Column(Name="analytical_ratings_fk", Index=5)
	@Table(Name="analytical_ratings")
	private AnalyticalRatings _analytical_ratings;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Integer getCustomerId() {
		return _customer_id;
	}

	public void setCustomerId(Integer customer_id) {
		_customer_id = customer_id;
	}

	public String getCustomerPricingModel() {
		return _customer_pricing_model;
	}

	public void setCustomerPricingModel(String customer_pricing_model) {
		_customer_pricing_model = customer_pricing_model;
	}

	public String getFuelType() {
		return _fuel_type;
	}

	public void setFuelType(String fuel_type) {
		_fuel_type = fuel_type;
	}

	public Timestamp getFuelingPurchaseHour() {
		return _fueling_purchase_hour;
	}

	public void setFuelingPurchaseHour(Timestamp fueling_purchase_hour) {
		_fueling_purchase_hour = fueling_purchase_hour;
	}

	public AnalyticalRatings getAnalyticalRatings() {
		return _analytical_ratings;
	}

	public void setAnalyticalRatings(AnalyticalRatings analytical_ratings) {
		_analytical_ratings = analytical_ratings;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_customer_id != null) {
			list.add("	customer_id: " + _customer_id);
		}
		if (_customer_pricing_model != null) {
			list.add("	customer_pricing_model: " + _customer_pricing_model);
		}
		if (_fuel_type != null) {
			list.add("	fuel_type: " + _fuel_type);
		}
		if (_fueling_purchase_hour != null) {
			list.add("	fueling_purchase_hour: " + _fueling_purchase_hour);
		}
		if (_analytical_ratings != null) {
			list.add("	analytical_ratings: " + _analytical_ratings);
		}
		return "table customers_ratings:\n" + String.join("\n", list);
	}

}