package db.entity;

import java.util.List;
import java.lang.Integer;
import db.entity.Customer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.Person;

@AutoGenerated
@Table(Name="driver")
public class Driver implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="customer_fk", Index=1)
	@Table(Name="customer")
	private Customer _customer;

	@Column(Name="person_fk", Index=2)
	@Table(Name="person")
	private Person _person;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Customer getCustomer() {
		return _customer;
	}

	public void setCustomer(Customer customer) {
		_customer = customer;
	}

	public Person getPerson() {
		return _person;
	}

	public void setPerson(Person person) {
		_person = person;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_customer != null) {
			list.add("	customer: " + _customer);
		}
		if (_person != null) {
			list.add("	person: " + _person);
		}
		return "table driver:\n" + String.join("\n", list);
	}

}