package db.entity;

import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.entity.FuelCompanyEnum;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.util.List;
import db.entity.Station;
import db.interfaces.IEntity;
import db.entity.SystemUser;
import java.lang.String;
import annotations.Table;
import db.entity.Person;

@AutoGenerated
@Table(Name="employee")
public class Employee implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="employee_role", Index=1)
	private String _employee_role;

	@Column(Name="affiliation", Index=2)
	private String _affiliation;

	@Column(Name="employee_num", Index=3)
	private Integer _employee_num;

	@Column(Name="person_fk", Index=4)
	@Table(Name="person")
	private Person _person;

	@Column(Name="station_fk", Index=5)
	@Table(Name="station")
	private Station _station;

	@Column(Name="system_user_fk", Index=6)
	@Table(Name="system_user")
	private SystemUser _system_user;

	@Column(Name="fuel_company_enum_fk", Index=7)
	@Table(Name="fuel_company_enum")
	private FuelCompanyEnum _fuel_company_enum;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getEmployeeRole() {
		return _employee_role;
	}

	public void setEmployeeRole(String employee_role) {
		_employee_role = employee_role;
	}

	public String getAffiliation() {
		return _affiliation;
	}

	public void setAffiliation(String affiliation) {
		_affiliation = affiliation;
	}

	public Integer getEmployeeNum() {
		return _employee_num;
	}

	public void setEmployeeNum(Integer employee_num) {
		_employee_num = employee_num;
	}

	public Person getPerson() {
		return _person;
	}

	public void setPerson(Person person) {
		_person = person;
	}

	public Station getStation() {
		return _station;
	}

	public void setStation(Station station) {
		_station = station;
	}

	public SystemUser getSystemUser() {
		return _system_user;
	}

	public void setSystemUser(SystemUser system_user) {
		_system_user = system_user;
	}

	public FuelCompanyEnum getFuelCompanyEnum() {
		return _fuel_company_enum;
	}

	public void setFuelCompanyEnum(FuelCompanyEnum fuel_company_enum) {
		_fuel_company_enum = fuel_company_enum;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_employee_role != null) {
			list.add("	employee_role: " + _employee_role);
		}
		if (_affiliation != null) {
			list.add("	affiliation: " + _affiliation);
		}
		if (_employee_num != null) {
			list.add("	employee_num: " + _employee_num);
		}
		if (_person != null) {
			list.add("	person: " + _person);
		}
		if (_station != null) {
			list.add("	station: " + _station);
		}
		if (_system_user != null) {
			list.add("	system_user: " + _system_user);
		}
		if (_fuel_company_enum != null) {
			list.add("	fuel_company_enum: " + _fuel_company_enum);
		}
		return "table employee:\n" + String.join("\n", list);
	}

}