package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="employee")
public class Employee implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="first_name", Index=1)
	private String _first_name;

	@Column(Name="last_name", Index=2)
	private String _last_name;

	@Column(Name="employee_id", Index=3)
	private String _employee_id;

	@Column(Name="email", Index=4)
	private String _email;

	@Column(Name="position", Index=5)
	private String _position;

	@Column(Name="organization_name", Index=6)
	private String _organization_name;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getFirstName() {
		return _first_name;
	}

	public void setFirstName(String first_name) {
		_first_name = first_name;
	}

	public String getLastName() {
		return _last_name;
	}

	public void setLastName(String last_name) {
		_last_name = last_name;
	}

	public String getEmployeeId() {
		return _employee_id;
	}

	public void setEmployeeId(String employee_id) {
		_employee_id = employee_id;
	}

	public String getEmail() {
		return _email;
	}

	public void setEmail(String email) {
		_email = email;
	}

	public String getPosition() {
		return _position;
	}

	public void setPosition(String position) {
		_position = position;
	}

	public String getOrganizationName() {
		return _organization_name;
	}

	public void setOrganizationName(String organization_name) {
		_organization_name = organization_name;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_first_name != null) {
			list.add("	first_name: " + _first_name);
		}
		if (_last_name != null) {
			list.add("	last_name: " + _last_name);
		}
		if (_employee_id != null) {
			list.add("	employee_id: " + _employee_id);
		}
		if (_email != null) {
			list.add("	email: " + _email);
		}
		if (_position != null) {
			list.add("	position: " + _position);
		}
		if (_organization_name != null) {
			list.add("	organization_name: " + _organization_name);
		}
		return "table employee:\n" + String.join("\n", list);
	}

}