package db.entity;

import java.lang.Integer;
import db.entity.Customer;
import annotations.Column;
import db.entity.SpecialSalesEnum;
import java.io.Serializable;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.sql.Timestamp;
import db.entity.FuelEnum;
import java.util.List;
import db.entity.Car;
import db.entity.Station;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;

@AutoGenerated
@Table(Name="fueling_purchase")
public class FuelingPurchase implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="date_time", Index=1)
	private Timestamp _date_time;

	@Column(Name="amount", Index=2)
	private Double _amount;

	@Column(Name="price_per_liter", Index=3)
	private Double _price_per_liter;

	@Column(Name="total_price", Index=4)
	private Double _total_price;

	@Column(Name="price_type", Index=5)
	private String _price_type;

	@Column(Name="car_fk", Index=6)
	@Table(Name="car")
	private Car _car;

	@Column(Name="special_sales_enum_fk", Index=7)
	@Table(Name="special_sales_enum")
	private SpecialSalesEnum _special_sales_enum;

	@Column(Name="station_fk", Index=8)
	@Table(Name="station")
	private Station _station;

	@Column(Name="fuel_enum_fk", Index=9)
	@Table(Name="fuel_enum")
	private FuelEnum _fuel_enum;

	@Column(Name="customer_fk", Index=10)
	@Table(Name="customer")
	private Customer _customer;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Timestamp getDateTime() {
		return _date_time;
	}

	public void setDateTime(Timestamp date_time) {
		_date_time = date_time;
	}

	public Double getAmount() {
		return _amount;
	}

	public void setAmount(Double amount) {
		_amount = amount;
	}

	public Double getPricePerLiter() {
		return _price_per_liter;
	}

	public void setPricePerLiter(Double price_per_liter) {
		_price_per_liter = price_per_liter;
	}

	public Double getTotalPrice() {
		return _total_price;
	}

	public void setTotalPrice(Double total_price) {
		_total_price = total_price;
	}

	public String getPriceType() {
		return _price_type;
	}

	public void setPriceType(String price_type) {
		_price_type = price_type;
	}

	public Car getCar() {
		return _car;
	}

	public void setCar(Car car) {
		_car = car;
	}

	public SpecialSalesEnum getSpecialSalesEnum() {
		return _special_sales_enum;
	}

	public void setSpecialSalesEnum(SpecialSalesEnum special_sales_enum) {
		_special_sales_enum = special_sales_enum;
	}

	public Station getStation() {
		return _station;
	}

	public void setStation(Station station) {
		_station = station;
	}

	public FuelEnum getFuelEnum() {
		return _fuel_enum;
	}

	public void setFuelEnum(FuelEnum fuel_enum) {
		_fuel_enum = fuel_enum;
	}

	public Customer getCustomer() {
		return _customer;
	}

	public void setCustomer(Customer customer) {
		_customer = customer;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_date_time != null) {
			list.add("	date_time: " + _date_time);
		}
		if (_amount != null) {
			list.add("	amount: " + _amount);
		}
		if (_price_per_liter != null) {
			list.add("	price_per_liter: " + _price_per_liter);
		}
		if (_total_price != null) {
			list.add("	total_price: " + _total_price);
		}
		if (_price_type != null) {
			list.add("	price_type: " + _price_type);
		}
		if (_car != null) {
			list.add("	car: " + _car);
		}
		if (_special_sales_enum != null) {
			list.add("	special_sales_enum: " + _special_sales_enum);
		}
		if (_station != null) {
			list.add("	station: " + _station);
		}
		if (_fuel_enum != null) {
			list.add("	fuel_enum: " + _fuel_enum);
		}
		if (_customer != null) {
			list.add("	customer: " + _customer);
		}
		return "table fueling_purchase:\n" + String.join("\n", list);
	}

}