package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import db.interfaces.IEnum;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="fuel_enum")
public class FuelEnum implements IEntity, IEnum, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="fuel_type_key", Index=1)
	private String _fuel_type_key;

	@Column(Name="max_price_per_type", Index=2)
	private Double _max_price_per_type;

	@Column(Name="supplier_price_per_liter", Index=3)
	private Double _supplier_price_per_liter;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	@Override
	public String getKey() {
		return _fuel_type_key;
	}

	public String getFuelTypeKey() {
		return _fuel_type_key;
	}

	public void setFuelTypeKey(String fuel_type_key) {
		_fuel_type_key = fuel_type_key;
	}

	public Double getMaxPricePerType() {
		return _max_price_per_type;
	}

	public void setMaxPricePerType(Double max_price_per_type) {
		_max_price_per_type = max_price_per_type;
	}

	public Double getSupplierPricePerLiter() {
		return _supplier_price_per_liter;
	}

	public void setSupplierPricePerLiter(Double supplier_price_per_liter) {
		_supplier_price_per_liter = supplier_price_per_liter;
	}

	@Override
	public boolean equals(Object other) {
		if (other instanceof IEnum) {
			return getKey().equals(((IEnum) other).getKey());
		}
		return false;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_fuel_type_key != null) {
			list.add("	fuel_type_key: " + _fuel_type_key);
		}
		if (_max_price_per_type != null) {
			list.add("	max_price_per_type: " + _max_price_per_type);
		}
		if (_supplier_price_per_liter != null) {
			list.add("	supplier_price_per_liter: " + _supplier_price_per_liter);
		}
		return "table fuel_enum:\n" + String.join("\n", list);
	}

}