package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.lang.Boolean;
import db.interfaces.IEnum;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="fuel_company_enum")
public class FuelCompanyEnum implements IEntity, IEnum, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="company_name_key", Index=1)
	private String _company_name_key;

	@Column(Name="company_discount", Index=2)
	private Double _company_discount;

	@Column(Name="company_discount_request", Index=3)
	private Double _company_discount_request;

	@Column(Name="request_handled", Index=4)
	private Boolean _request_handled;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	@Override
	public String getKey() {
		return _company_name_key;
	}

	public String getCompanyNameKey() {
		return _company_name_key;
	}

	public void setCompanyNameKey(String company_name_key) {
		_company_name_key = company_name_key;
	}

	public Double getCompanyDiscount() {
		return _company_discount;
	}

	public void setCompanyDiscount(Double company_discount) {
		_company_discount = company_discount;
	}

	public Double getCompanyDiscountRequest() {
		return _company_discount_request;
	}

	public void setCompanyDiscountRequest(Double company_discount_request) {
		_company_discount_request = company_discount_request;
	}

	public Boolean getRequestHandled() {
		return _request_handled;
	}

	public void setRequestHandled(Boolean request_handled) {
		_request_handled = request_handled;
	}

	@Override
	public boolean equals(Object other) {
		if (other instanceof IEnum) {
			return getKey().equals(((IEnum) other).getKey());
		}
		return false;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_company_name_key != null) {
			list.add("	company_name_key: " + _company_name_key);
		}
		if (_company_discount != null) {
			list.add("	company_discount: " + _company_discount);
		}
		if (_company_discount_request != null) {
			list.add("	company_discount_request: " + _company_discount_request);
		}
		if (_request_handled != null) {
			list.add("	request_handled: " + _request_handled);
		}
		return "table fuel_company_enum:\n" + String.join("\n", list);
	}

}