package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.lang.Boolean;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import db.entity.FuelCompanyEnum;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.FuelEnum;

@AutoGenerated
@Table(Name="fuel_in_company")
public class FuelInCompany implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="company_price", Index=1)
	private Double _company_price;

	@Column(Name="fuel_enum_fk", Index=2)
	@Table(Name="fuel_enum")
	private FuelEnum _fuel_enum;

	@Column(Name="fuel_company_enum_fk", Index=3)
	@Table(Name="fuel_company_enum")
	private FuelCompanyEnum _fuel_company_enum;

	@Column(Name="company_price_request", Index=4)
	private Double _company_price_request;

	@Column(Name="request_handled", Index=5)
	private Boolean _request_handled;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Double getCompanyPrice() {
		return _company_price;
	}

	public void setCompanyPrice(Double company_price) {
		_company_price = company_price;
	}

	public FuelEnum getFuelEnum() {
		return _fuel_enum;
	}

	public void setFuelEnum(FuelEnum fuel_enum) {
		_fuel_enum = fuel_enum;
	}

	public FuelCompanyEnum getFuelCompanyEnum() {
		return _fuel_company_enum;
	}

	public void setFuelCompanyEnum(FuelCompanyEnum fuel_company_enum) {
		_fuel_company_enum = fuel_company_enum;
	}

	public Double getCompanyPriceRequest() {
		return _company_price_request;
	}

	public void setCompanyPriceRequest(Double company_price_request) {
		_company_price_request = company_price_request;
	}

	public Boolean getRequestHandled() {
		return _request_handled;
	}

	public void setRequestHandled(Boolean request_handled) {
		_request_handled = request_handled;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_company_price != null) {
			list.add("	company_price: " + _company_price);
		}
		if (_fuel_enum != null) {
			list.add("	fuel_enum: " + _fuel_enum);
		}
		if (_fuel_company_enum != null) {
			list.add("	fuel_company_enum: " + _fuel_company_enum);
		}
		if (_company_price_request != null) {
			list.add("	company_price_request: " + _company_price_request);
		}
		if (_request_handled != null) {
			list.add("	request_handled: " + _request_handled);
		}
		return "table fuel_in_company:\n" + String.join("\n", list);
	}

}