package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import db.interfaces.IEnum;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="home_heating_discount_enum")
public class HomeHeatingDiscountEnum implements IEntity, IEnum, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="discount_description_key", Index=1)
	private String _discount_description_key;

	@Column(Name="discount", Index=2)
	private Double _discount;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	@Override
	public String getKey() {
		return _discount_description_key;
	}

	public String getDiscountDescriptionKey() {
		return _discount_description_key;
	}

	public void setDiscountDescriptionKey(String discount_description_key) {
		_discount_description_key = discount_description_key;
	}

	public Double getDiscount() {
		return _discount;
	}

	public void setDiscount(Double discount) {
		_discount = discount;
	}

	@Override
	public boolean equals(Object other) {
		if (other instanceof IEnum) {
			return getKey().equals(((IEnum) other).getKey());
		}
		return false;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_discount_description_key != null) {
			list.add("	discount_description_key: " + _discount_description_key);
		}
		if (_discount != null) {
			list.add("	discount: " + _discount);
		}
		return "table home_heating_discount_enum:\n" + String.join("\n", list);
	}

}