package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="marketing_manager_reports")
public class MarketingManagerReports implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="report_type", Index=1)
	private String _report_type;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getReportType() {
		return _report_type;
	}

	public void setReportType(String report_type) {
		_report_type = report_type;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_report_type != null) {
			list.add("	report_type: " + _report_type);
		}
		return "table marketing_manager_reports:\n" + String.join("\n", list);
	}

}