package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import db.interfaces.IEnum;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="order_urgency_enum")
public class OrderUrgencyEnum implements IEntity, IEnum, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="order_urgency_key", Index=1)
	private String _order_urgency_key;

	@Column(Name="extra_delivery_price", Index=2)
	private Double _extra_delivery_price;

	@Column(Name="estimated_delivery_hours", Index=3)
	private Double _estimated_delivery_hours;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	@Override
	public String getKey() {
		return _order_urgency_key;
	}

	public String getOrderUrgencyKey() {
		return _order_urgency_key;
	}

	public void setOrderUrgencyKey(String order_urgency_key) {
		_order_urgency_key = order_urgency_key;
	}

	public Double getExtraDeliveryPrice() {
		return _extra_delivery_price;
	}

	public void setExtraDeliveryPrice(Double extra_delivery_price) {
		_extra_delivery_price = extra_delivery_price;
	}

	public Double getEstimatedDeliveryHours() {
		return _estimated_delivery_hours;
	}

	public void setEstimatedDeliveryHours(Double estimated_delivery_hours) {
		_estimated_delivery_hours = estimated_delivery_hours;
	}

	@Override
	public boolean equals(Object other) {
		if (other instanceof IEnum) {
			return getKey().equals(((IEnum) other).getKey());
		}
		return false;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_order_urgency_key != null) {
			list.add("	order_urgency_key: " + _order_urgency_key);
		}
		if (_extra_delivery_price != null) {
			list.add("	extra_delivery_price: " + _extra_delivery_price);
		}
		if (_estimated_delivery_hours != null) {
			list.add("	estimated_delivery_hours: " + _estimated_delivery_hours);
		}
		return "table order_urgency_enum:\n" + String.join("\n", list);
	}

}