package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.lang.Boolean;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="payment")
public class Payment implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="credit_card_number", Index=1)
	private String _credit_card_number;

	@Column(Name="expiration_date_year", Index=2)
	private Integer _expiration_date_year;

	@Column(Name="expiration_date_month", Index=3)
	private Integer _expiration_date_month;

	@Column(Name="cvv", Index=4)
	private Integer _cvv;

	@Column(Name="company_credit_card", Index=5)
	private String _company_credit_card;

	@Column(Name="cash", Index=6)
	private Boolean _cash;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getCreditCardNumber() {
		return _credit_card_number;
	}

	public void setCreditCardNumber(String credit_card_number) {
		_credit_card_number = credit_card_number;
	}

	public Integer getExpirationDateYear() {
		return _expiration_date_year;
	}

	public void setExpirationDateYear(Integer expiration_date_year) {
		_expiration_date_year = expiration_date_year;
	}

	public Integer getExpirationDateMonth() {
		return _expiration_date_month;
	}

	public void setExpirationDateMonth(Integer expiration_date_month) {
		_expiration_date_month = expiration_date_month;
	}

	public Integer getCvv() {
		return _cvv;
	}

	public void setCvv(Integer cvv) {
		_cvv = cvv;
	}

	public String getCompanyCreditCard() {
		return _company_credit_card;
	}

	public void setCompanyCreditCard(String company_credit_card) {
		_company_credit_card = company_credit_card;
	}

	public Boolean getCash() {
		return _cash;
	}

	public void setCash(Boolean cash) {
		_cash = cash;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_credit_card_number != null) {
			list.add("	credit_card_number: " + _credit_card_number);
		}
		if (_expiration_date_year != null) {
			list.add("	expiration_date_year: " + _expiration_date_year);
		}
		if (_expiration_date_month != null) {
			list.add("	expiration_date_month: " + _expiration_date_month);
		}
		if (_cvv != null) {
			list.add("	cvv: " + _cvv);
		}
		if (_company_credit_card != null) {
			list.add("	company_credit_card: " + _company_credit_card);
		}
		if (_cash != null) {
			list.add("	cash: " + _cash);
		}
		return "table payment:\n" + String.join("\n", list);
	}

}