package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="person")
public class Person implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="first_name", Index=1)
	private String _first_name;

	@Column(Name="last_name", Index=2)
	private String _last_name;

	@Column(Name="email", Index=3)
	private String _email;

	@Column(Name="phone_number", Index=4)
	private String _phone_number;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getFirstName() {
		return _first_name;
	}

	public void setFirstName(String first_name) {
		_first_name = first_name;
	}

	public String getLastName() {
		return _last_name;
	}

	public void setLastName(String last_name) {
		_last_name = last_name;
	}

	public String getEmail() {
		return _email;
	}

	public void setEmail(String email) {
		_email = email;
	}

	public String getPhoneNumber() {
		return _phone_number;
	}

	public void setPhoneNumber(String phone_number) {
		_phone_number = phone_number;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_first_name != null) {
			list.add("	first_name: " + _first_name);
		}
		if (_last_name != null) {
			list.add("	last_name: " + _last_name);
		}
		if (_email != null) {
			list.add("	email: " + _email);
		}
		if (_phone_number != null) {
			list.add("	phone_number: " + _phone_number);
		}
		return "table person:\n" + String.join("\n", list);
	}

}