package db.entity;

import java.util.List;
import db.entity.Reports;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.CheckingEnum;

@AutoGenerated
@Table(Name="reports_info")
public class ReportsInfo implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="year", Index=1)
	private Integer _year;

	@Column(Name="quarter", Index=2)
	private Integer _quarter;

	@Column(Name="report_type", Index=3)
	private String _report_type;

	@Column(Name="station_name", Index=4)
	private String _station_name;

	@Column(Name="reports_fk", Index=5)
	@Table(Name="reports")
	private Reports _reports;

	@Column(Name="checking_enum_fk", Index=6)
	@Table(Name="checking_enum")
	private CheckingEnum _checking_enum;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Integer getYear() {
		return _year;
	}

	public void setYear(Integer year) {
		_year = year;
	}

	public Integer getQuarter() {
		return _quarter;
	}

	public void setQuarter(Integer quarter) {
		_quarter = quarter;
	}

	public String getReportType() {
		return _report_type;
	}

	public void setReportType(String report_type) {
		_report_type = report_type;
	}

	public String getStationName() {
		return _station_name;
	}

	public void setStationName(String station_name) {
		_station_name = station_name;
	}

	public Reports getReports() {
		return _reports;
	}

	public void setReports(Reports reports) {
		_reports = reports;
	}

	public CheckingEnum getCheckingEnum() {
		return _checking_enum;
	}

	public void setCheckingEnum(CheckingEnum checking_enum) {
		_checking_enum = checking_enum;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_year != null) {
			list.add("	year: " + _year);
		}
		if (_quarter != null) {
			list.add("	quarter: " + _quarter);
		}
		if (_report_type != null) {
			list.add("	report_type: " + _report_type);
		}
		if (_station_name != null) {
			list.add("	station_name: " + _station_name);
		}
		if (_reports != null) {
			list.add("	reports: " + _reports);
		}
		if (_checking_enum != null) {
			list.add("	checking_enum: " + _checking_enum);
		}
		return "table reports_info:\n" + String.join("\n", list);
	}

}