package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import db.entity.SpecialSalesEnum;
import java.io.Serializable;
import db.interfaces.IEntity;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.sql.Timestamp;

@AutoGenerated
@Table(Name="special_sales_history")
public class SpecialSalesHistory implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="start_time", Index=1)
	private Timestamp _start_time;

	@Column(Name="end_time", Index=2)
	private Timestamp _end_time;

	@Column(Name="special_sales_enum_fk", Index=3)
	@Table(Name="special_sales_enum")
	private SpecialSalesEnum _special_sales_enum;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Timestamp getStartTime() {
		return _start_time;
	}

	public void setStartTime(Timestamp start_time) {
		_start_time = start_time;
	}

	public Timestamp getEndTime() {
		return _end_time;
	}

	public void setEndTime(Timestamp end_time) {
		_end_time = end_time;
	}

	public SpecialSalesEnum getSpecialSalesEnum() {
		return _special_sales_enum;
	}

	public void setSpecialSalesEnum(SpecialSalesEnum special_sales_enum) {
		_special_sales_enum = special_sales_enum;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_start_time != null) {
			list.add("	start_time: " + _start_time);
		}
		if (_end_time != null) {
			list.add("	end_time: " + _end_time);
		}
		if (_special_sales_enum != null) {
			list.add("	special_sales_enum: " + _special_sales_enum);
		}
		return "table special_sales_history:\n" + String.join("\n", list);
	}

}