package db.entity;

import java.util.List;
import java.lang.Integer;
import db.entity.Station;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.FuelEnum;

@AutoGenerated
@Table(Name="stations_fuel")
public class StationsFuel implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="current_amount", Index=1)
	private Double _current_amount;

	@Column(Name="fuel_low_level", Index=2)
	private Double _fuel_low_level;

	@Column(Name="max_amount", Index=3)
	private Double _max_amount;

	@Column(Name="fuel_enum_fk", Index=4)
	@Table(Name="fuel_enum")
	private FuelEnum _fuel_enum;

	@Column(Name="station_fk", Index=5)
	@Table(Name="station")
	private Station _station;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Double getCurrentAmount() {
		return _current_amount;
	}

	public void setCurrentAmount(Double current_amount) {
		_current_amount = current_amount;
	}

	public Double getFuelLowLevel() {
		return _fuel_low_level;
	}

	public void setFuelLowLevel(Double fuel_low_level) {
		_fuel_low_level = fuel_low_level;
	}

	public Double getMaxAmount() {
		return _max_amount;
	}

	public void setMaxAmount(Double max_amount) {
		_max_amount = max_amount;
	}

	public FuelEnum getFuelEnum() {
		return _fuel_enum;
	}

	public void setFuelEnum(FuelEnum fuel_enum) {
		_fuel_enum = fuel_enum;
	}

	public Station getStation() {
		return _station;
	}

	public void setStation(Station station) {
		_station = station;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_current_amount != null) {
			list.add("	current_amount: " + _current_amount);
		}
		if (_fuel_low_level != null) {
			list.add("	fuel_low_level: " + _fuel_low_level);
		}
		if (_max_amount != null) {
			list.add("	max_amount: " + _max_amount);
		}
		if (_fuel_enum != null) {
			list.add("	fuel_enum: " + _fuel_enum);
		}
		if (_station != null) {
			list.add("	station: " + _station);
		}
		return "table stations_fuel:\n" + String.join("\n", list);
	}

}