package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import db.entity.FuelCompanyEnum;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.Address;

@AutoGenerated
@Table(Name="station")
public class Station implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="station_name", Index=1)
	private String _station_name;

	@Column(Name="phone_number", Index=2)
	private String _phone_number;

	@Column(Name="address_fk", Index=3)
	@Table(Name="address")
	private Address _address;

	@Column(Name="fuel_company_enum_fk", Index=4)
	@Table(Name="fuel_company_enum")
	private FuelCompanyEnum _fuel_company_enum;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getStationName() {
		return _station_name;
	}

	public void setStationName(String station_name) {
		_station_name = station_name;
	}

	public String getPhoneNumber() {
		return _phone_number;
	}

	public void setPhoneNumber(String phone_number) {
		_phone_number = phone_number;
	}

	public Address getAddress() {
		return _address;
	}

	public void setAddress(Address address) {
		_address = address;
	}

	public FuelCompanyEnum getFuelCompanyEnum() {
		return _fuel_company_enum;
	}

	public void setFuelCompanyEnum(FuelCompanyEnum fuel_company_enum) {
		_fuel_company_enum = fuel_company_enum;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_station_name != null) {
			list.add("	station_name: " + _station_name);
		}
		if (_phone_number != null) {
			list.add("	phone_number: " + _phone_number);
		}
		if (_address != null) {
			list.add("	address: " + _address);
		}
		if (_fuel_company_enum != null) {
			list.add("	fuel_company_enum: " + _fuel_company_enum);
		}
		return "table station:\n" + String.join("\n", list);
	}

}