package db.entity;

import java.lang.Integer;
import annotations.Column;
import java.io.Serializable;
import annotations.AutoGenerated;
import java.util.ArrayList;
import java.sql.Timestamp;
import db.entity.FuelEnum;
import java.util.List;
import db.entity.Station;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;

@AutoGenerated
@Table(Name="station_supply_order")
public class StationSupplyOrder implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="order_id", Index=1)
	private Integer _order_id;

	@Column(Name="order_date", Index=2)
	private Timestamp _order_date;

	@Column(Name="amount", Index=3)
	private Double _amount;

	@Column(Name="order_status", Index=4)
	private String _order_status;

	@Column(Name="total_price", Index=5)
	private Double _total_price;

	@Column(Name="fuel_enum_fk", Index=6)
	@Table(Name="fuel_enum")
	private FuelEnum _fuel_enum;

	@Column(Name="station_fk", Index=7)
	@Table(Name="station")
	private Station _station;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public Integer getOrderId() {
		return _order_id;
	}

	public void setOrderId(Integer order_id) {
		_order_id = order_id;
	}

	public Timestamp getOrderDate() {
		return _order_date;
	}

	public void setOrderDate(Timestamp order_date) {
		_order_date = order_date;
	}

	public Double getAmount() {
		return _amount;
	}

	public void setAmount(Double amount) {
		_amount = amount;
	}

	public String getOrderStatus() {
		return _order_status;
	}

	public void setOrderStatus(String order_status) {
		_order_status = order_status;
	}

	public Double getTotalPrice() {
		return _total_price;
	}

	public void setTotalPrice(Double total_price) {
		_total_price = total_price;
	}

	public FuelEnum getFuelEnum() {
		return _fuel_enum;
	}

	public void setFuelEnum(FuelEnum fuel_enum) {
		_fuel_enum = fuel_enum;
	}

	public Station getStation() {
		return _station;
	}

	public void setStation(Station station) {
		_station = station;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_order_id != null) {
			list.add("	order_id: " + _order_id);
		}
		if (_order_date != null) {
			list.add("	order_date: " + _order_date);
		}
		if (_amount != null) {
			list.add("	amount: " + _amount);
		}
		if (_order_status != null) {
			list.add("	order_status: " + _order_status);
		}
		if (_total_price != null) {
			list.add("	total_price: " + _total_price);
		}
		if (_fuel_enum != null) {
			list.add("	fuel_enum: " + _fuel_enum);
		}
		if (_station != null) {
			list.add("	station: " + _station);
		}
		return "table station_supply_order:\n" + String.join("\n", list);
	}

}