package db.entity;

import java.util.List;
import java.lang.Integer;
import db.entity.Station;
import annotations.Column;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;
import db.entity.FuelEnum;

@AutoGenerated
@Table(Name="station_manager_reports")
public class StationManagerReports implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="report_type", Index=1)
	private String _report_type;

	@Column(Name="report_quarter", Index=2)
	private String _report_quarter;

	@Column(Name="report_year", Index=3)
	private String _report_year;

	@Column(Name="amount", Index=4)
	private Double _amount;

	@Column(Name="price", Index=5)
	private Double _price;

	@Column(Name="total_price", Index=6)
	private Double _total_price;

	@Column(Name="fuel_enum_fk", Index=7)
	@Table(Name="fuel_enum")
	private FuelEnum _fuel_enum;

	@Column(Name="station_fk", Index=8)
	@Table(Name="station")
	private Station _station;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getReportType() {
		return _report_type;
	}

	public void setReportType(String report_type) {
		_report_type = report_type;
	}

	public String getReportQuarter() {
		return _report_quarter;
	}

	public void setReportQuarter(String report_quarter) {
		_report_quarter = report_quarter;
	}

	public String getReportYear() {
		return _report_year;
	}

	public void setReportYear(String report_year) {
		_report_year = report_year;
	}

	public Double getAmount() {
		return _amount;
	}

	public void setAmount(Double amount) {
		_amount = amount;
	}

	public Double getPrice() {
		return _price;
	}

	public void setPrice(Double price) {
		_price = price;
	}

	public Double getTotalPrice() {
		return _total_price;
	}

	public void setTotalPrice(Double total_price) {
		_total_price = total_price;
	}

	public FuelEnum getFuelEnum() {
		return _fuel_enum;
	}

	public void setFuelEnum(FuelEnum fuel_enum) {
		_fuel_enum = fuel_enum;
	}

	public Station getStation() {
		return _station;
	}

	public void setStation(Station station) {
		_station = station;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_report_type != null) {
			list.add("	report_type: " + _report_type);
		}
		if (_report_quarter != null) {
			list.add("	report_quarter: " + _report_quarter);
		}
		if (_report_year != null) {
			list.add("	report_year: " + _report_year);
		}
		if (_amount != null) {
			list.add("	amount: " + _amount);
		}
		if (_price != null) {
			list.add("	price: " + _price);
		}
		if (_total_price != null) {
			list.add("	total_price: " + _total_price);
		}
		if (_fuel_enum != null) {
			list.add("	fuel_enum: " + _fuel_enum);
		}
		if (_station != null) {
			list.add("	station: " + _station);
		}
		return "table station_manager_reports:\n" + String.join("\n", list);
	}

}