package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import db.interfaces.IEnum;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.Double;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="subscription_plan_rates_enum")
public class SubscriptionPlanRatesEnum implements IEntity, IEnum, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="plan_type_key", Index=1)
	private String _plan_type_key;

	@Column(Name="discount", Index=2)
	private Double _discount;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	@Override
	public String getKey() {
		return _plan_type_key;
	}

	public String getPlanTypeKey() {
		return _plan_type_key;
	}

	public void setPlanTypeKey(String plan_type_key) {
		_plan_type_key = plan_type_key;
	}

	public Double getDiscount() {
		return _discount;
	}

	public void setDiscount(Double discount) {
		_discount = discount;
	}

	@Override
	public boolean equals(Object other) {
		if (other instanceof IEnum) {
			return getKey().equals(((IEnum) other).getKey());
		}
		return false;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_plan_type_key != null) {
			list.add("	plan_type_key: " + _plan_type_key);
		}
		if (_discount != null) {
			list.add("	discount: " + _discount);
		}
		return "table subscription_plan_rates_enum:\n" + String.join("\n", list);
	}

}