package db.entity;

import java.util.List;
import java.lang.Integer;
import annotations.Column;
import java.lang.Boolean;
import java.io.Serializable;
import db.interfaces.IEntity;
import java.lang.String;
import annotations.Table;
import annotations.AutoGenerated;
import java.util.ArrayList;

@AutoGenerated
@Table(Name="system_user")
public class SystemUser implements IEntity, Serializable {

	private static final long serialVersionUID = 1L;

	@Column(Name="id", Index=0)
	private Integer _id;

	@Column(Name="user_name", Index=1)
	private String _user_name;

	@Column(Name="user_password", Index=2)
	private String _user_password;

	@Column(Name="online_status", Index=3)
	private Boolean _online_status;

	@Column(Name="permission", Index=4)
	private String _permission;

	public Integer getId() {
		return _id;
	}

	public void setId(Integer id) {
		_id = id;
	}

	public String getUserName() {
		return _user_name;
	}

	public void setUserName(String user_name) {
		_user_name = user_name;
	}

	public String getUserPassword() {
		return _user_password;
	}

	public void setUserPassword(String user_password) {
		_user_password = user_password;
	}

	public Boolean getOnlineStatus() {
		return _online_status;
	}

	public void setOnlineStatus(Boolean online_status) {
		_online_status = online_status;
	}

	public String getPermission() {
		return _permission;
	}

	public void setPermission(String permission) {
		_permission = permission;
	}

	public String toString() {
		List<String> list = new ArrayList<String>();
		if (_id != null) {
			list.add("	id: " + _id);
		}
		if (_user_name != null) {
			list.add("	user_name: " + _user_name);
		}
		if (_user_password != null) {
			list.add("	user_password: " + _user_password);
		}
		if (_online_status != null) {
			list.add("	online_status: " + _online_status);
		}
		if (_permission != null) {
			list.add("	permission: " + _permission);
		}
		return "table system_user:\n" + String.join("\n", list);
	}

}